### ISSUE TITLE
Java 17 Parser Support

### ISSUE THREAD

**Issue by Jonpez2** [openrewrite/rewrite#1501]
- [x] [Support `instanceof` pattern matching](https://github.com/openrewrite/rewrite/issues/2158)
- [x] [Support multi-line strings](https://github.com/openrewrite/rewrite/issues/2163)
- [x] [Support switch expressions](https://github.com/openrewrite/rewrite/issues/2164)
- [x] [Support records](https://github.com/openrewrite/rewrite/issues/2165)

I’m not sure if this belongs in this repo or the main openrewrite repo but… what are the plans for support of java 17 record syntax and all the upcoming pattern matching features please?

Thank you - and thanks for the amazing tool!

**Comment by Jonpez2** [comment]
Any thoughts/plans on this one please?

Thanks!

**Comment by Jonpez2** [comment]
As an interim, would it be hard to ensure that OpenRewrite always fails when encountering constructs it doesn't understand?  At the moment OR will sometimes successfully parse, but the result when actually passed through a recipe is gibberish.  I'm trying to find a minimal reproducible case but haven't got one yet.

**Comment by Jonpez2** [comment]
Turns out a minimal reproducible example case is just ‘anything with a variable-declaring instanceof expression’. So, OR processing the below expression will result in gibberish. Note that this isn’t the only thing - sometimes record syntax makes it sad as well. 

if( foo instanceof String s && s.isEmpty() ) {
   ….
}

**Comment by traceyyoshima** [comment]
Hi @Jonpez2 , thanks for all the information!
I just want to add a comment so that anyone who is watching this issue knows we haven't forgotten about it.
I think Java 17 support will be one of @tkvangorder 's next big projects.

**Comment by Jonpez2** [comment]
Well that’s good news thank you.

**Comment by Jonpez2** [comment]
Is there any way to get the pulse on the support for java 17+ please?  Thank you!

**Comment by traceyyoshima** [comment]
Hi @Jonpez2, @tkvangorder has looked into the Jigsaw constraints and has a promising solution. Development of Java 17 support is in process.

**Comment by Jonpez2** [comment]
Superb! That includes the syntactic support as well as the runtime support, correct?

**Comment by Jonpez2** [comment]
I ask because it’s the syntax changes in jdk 17 that are killing my use of OR, not the jigsaw runtime restrictions

**Comment by Jonpez2** [comment]
Also looks like we might get this bit of awesome in jdk19 - https://openjdk.java.net/jeps/405. Java’s getting hard to keep up with! :)

**Comment by tkvangorder** [comment]
@Jonpez2 Yes, the plan is first to get the parser working without being constrained by jigsaw and then to implement the additional language features.

**Comment by Jonpez2** [comment]
Ok cool. I can’t wait!

**Comment by Jonpez2** [comment]
I see you released jdk 17 runtime support. Awesome to see movement, thank you!

**Comment by tkvangorder** [comment]
Yep, we are halfway there, we can load the parser in jigsaw without security exceptions, the next step is adding 17 language features. Hoping to work on that soon, it has been a busy couple of weeks

**Comment by Jonpez2** [comment]
Super news. Thank you so much for the hard work!

**Comment by Jonpez2** [comment]
Hello!  How is this coming along please?  Thank you!

**Comment by tkvangorder** [comment]
Hi, @Jonpez2 This is still on our TODO list, thanks for your patience.

**Comment by Jonpez2** [comment]
OK.  I wonder if you should do all the way through to jdk19, since that's coming in like 2 months...

**Comment by Jonpez2** [comment]
I knojw it's a lot to ask, but what kind of timeframe should I have in mind here please?  Just wondering whether to find myself some kind of a stopgap for the interim...

Thank you!

**Comment by Jonpez2** [comment]
Ping?  Thanks!

**Comment by Jonpez2** [comment]
Superb! That includes the syntactic support as well as the runtime support,
correct?

**Comment by jkschneider** [comment]
That's correct @Jonpez2. Just finished up switch expressions on my trip home. Records are next!

**Comment by Jonpez2** [comment]
Yay!  thank you!

**Comment by Jonpez2** [comment]
Ooh exciting thank you!!
